services:
    pmm_labo.ber_creation:
        class: PMM\LaboBundle\BerCreation\BerCreation
        tags:
            - { name: doctrine.event_listener, event: postPersist}
            - { name: doctrine.event_listener, event: postUpdate}
            - { name: doctrine.event_listener, event: postRemove}